# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates (every 1 hours daily)
  schedule:
    - cron: '0 0/1 * * *'
  # Lines below let you run workflow manually and on each commit
  # workflow_dispatch:
  # push: {branches: ["master", "main"]}


jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: Manav-SM/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_SECRET }}
          user: Manav-SM
          template: classic
          base: header, activity, community, repositories
          config_timezone: Asia/Kolkata

  intro-metrics:
    runs-on: ubuntu-latest
    steps:          
      - name: intro
        uses: Manav-SM/metrics@latest
        with:
          filename: intro.svg
          token: ${{ secrets.PERSONAL_TOKEN }}
          template: classic
          base: ""
          plugin_introduction: yes
          plugin_introduction_title: yes
          config_timezone: Asia/Kolkata

  achievements-metrics:
    runs-on: ubuntu-latest
    steps:          
      - name: achievements info
        uses: Manav-SM/metrics@latest
        with:
          filename: achievements.svg
          token: ${{ secrets.PERSONAL_TOKEN }}
          template: classic
          base: ""
          plugin_achievements: yes
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: E
          config_timezone: Asia/Kolkata
          
  stars-metrics:
    runs-on: ubuntu-latest
    steps:          
      - name: stars info
        uses: Manav-SM/metrics@latest
        with:
          filename: stars.svg
          token: ${{ secrets.PERSONAL_TOKEN }}
          template: classic
          base: ""
          plugin_stars: yes
          plugin_stars_limit: 5
          config_timezone: Asia/Kolkata
          
  languages-metrics:
    runs-on: ubuntu-latest
    steps:          
      - name: language info
        uses: Manav-SM/metrics@latest
        with:
          filename: languages.svg
          token: ${{ secrets.PERSONAL_TOKEN }}
          template: classic
          base: ""
          plugin_languages: yes
          plugin_languages_sections: most-used, recently-used           # Display most used and recently used
          plugin_languages_colors: "0:orange, javascript:#ff0000, ..."  # Make most used languages orange and JavaScript red
          plugin_languages_aliases: "JavaScript:JS, TypeScript:TS, ..." # Customize languages names with aliases
          plugin_languages_details: bytes-size, percentage              # Additionally display total bytes size and percentage
          plugin_languages_threshold: 0%                               # Hides all languages less than 2%
          plugin_languages_limit: 10                                     # Display up to 10 languages
          plugin_languages_categories: programming                      # Display only languages that match these categories in most-used section
          plugin_languages_recent_categories: markup, programming, data # Display only languages that match these categories in recently-used section
          plugin_languages_indepth: yes                                  # Get indepth stats (see documentation before enabling)
          plugin_languages_recent_load: 500
          config_timezone: Asia/Kolkata

  website-metrics:
    runs-on: ubuntu-latest
    steps:          
      - name: website info
        uses: Manav-SM/metrics@latest
        with:
          filename: website.svg
          token: ${{ secrets.PERSONAL_TOKEN }}
          template: classic
          base: ""
          plugin_pagespeed: yes
          plugin_pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }}
          plugin_pagespeed_detailed: yes
          plugin_pagespeed_url: .user.website
          config_timezone: Asia/Kolkata
          
  habit-metrics:
    runs-on: ubuntu-latest
    steps:          
      - name: habit info
        uses: Manav-SM/metrics@latest
        with:
          filename: habit.svg
          token: ${{ secrets.PERSONAL_TOKEN }}
          template: classic
          base: ""
          plugin_habits: yes
          plugin_habits_from: 500       # Use 500 events to compute habits
          plugin_habits_days: 365        # Keep only events from last 365 days
          plugin_habits_facts: yes      # Display facts section
          plugin_habits_charts: yes     # Display charts section
          plugin_habits_trim: yes       # Trim unused hours on daily chart
          plugin_gists: yes
          config_timezone: Asia/Kolkata
          
  calendar-metrics:
    runs-on: ubuntu-latest
    steps:          
      - name: calender info
        uses: Manav-SM/metrics@latest
        with:
          filename: calender.svg
          token: ${{ secrets.PERSONAL_TOKEN }}
          template: classic
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          config_timezone: Asia/Kolkata        
