# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates (every 8 hours daily)
  schedule:
    - cron: '0 0,8,16 * * *'
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
  
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: Manav-SM/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_SECRET }}
          user: Manav-SM
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Kolkata
          plugin_notable: yes
          config_padding: 13%


  intro-metrics:
    runs-on: ubuntu-latest
    steps:          
      - name: intro
        uses: Manav-SM/metrics@latest
        with:
          filename: intro.svg
          token: ${{ secrets.METRICS_TOKEN }}
          template: classic
          base: ""
          plugin_stars: yes
          plugin_stars_limit: 5
          config_padding: 13%
          plugin_introduction: yes
          plugin_introduction_title: yes
          config_timezone: Asia/Kolkata

  achievements-metrics:
    runs-on: ubuntu-latest
    steps:          
      - name: achievements info
        uses: Manav-SM/metrics@latest
        with:
          filename: achievements.svg
          token: ${{ secrets.METRICS_TOKEN }}
          template: classic
          base: ""
          plugin_stars: yes
          plugin_stars_limit: 5
          config_padding: 13%
          plugin_achievements: yes
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: E
          config_timezone: Asia/Kolkata
          
  languages-metrics:
    runs-on: ubuntu-latest
    steps:          
      - name: language info
        uses: Manav-SM/metrics@latest
        with:
          filename: languages.svg
          token: ${{ secrets.METRICS_TOKEN }}
          template: classic
          base: ""
          plugin_stars: yes
          plugin_stars_limit: 5
          config_padding: 13%
          plugin_languages: yes
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent.days: 14
          plugin_languages_recent.load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          config_timezone: Asia/Kolkata

  website-metrics:
    runs-on: ubuntu-latest
    steps:          
      - name: website info
        uses: Manav-SM/metrics@latest
        with:
          filename: website.svg
          token: ${{ secrets.METRICS_TOKEN }}
          template: classic
          base: ""
          plugin_stars: yes
          plugin_stars_limit: 5
          config_padding: 13%
          plugin_pagespeed: yes
          plugin_pagespeed_detailed: yes
          plugin_pagespeed_url: .user.website
          config_timezone: Asia/Kolkata
          
  habit-metrics:
    runs-on: ubuntu-latest
    steps:          
      - name: habit info
        uses: Manav-SM/metrics@latest
        with:
          filename: habit.svg
          token: ${{ secrets.METRICS_TOKEN }}
          template: classic
          base: ""
          config_padding: 13%
          plugin_isocalendar: yes
          plugin_isocalendar_duration: year
          plugin_habits: yes
          plugin_habits_from: 200       # Use 200 events to compute habits
          plugin_habits_days: 14        # Keep only events from last 14 days
          plugin_habits_facts: yes      # Display facts section
          plugin_habits_charts: yes     # Display charts section
          plugin_habits_trim: yes       # Trim unused hours on daily chart
          plugin_licenses: yes
          plugin_licenses_legal: yes
          plugin_lines: yes
          config_timezone: Asia/Kolkata

