# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_SECRET }}

          # Options
          user: Manav-SM
          template: repository
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Kolkata
          plugin_achievements: yes
          plugin_achievements_secrets: yes
          plugin_languages: yes
          plugin_traffic: yes
          plugin_languages_colors: "0:orange, javascript:#ff0000, ..."  # Make most used languages orange and JavaScript red
          plugin_languages_aliases: "JavaScript:JS, TypeScript:TS, ..." # Customize languages names with aliases
          plugin_languages_details: bytes-size, percentage              # Additionally display total bytes size and percentage
          plugin_la nguages_threshold: 0%                               # Hides all languages less than 2%
          plugin_languages_limit: 8                                     # Display up to 8 languages
          plugin_languages_sections: most-used, recently-used           # Display most used and recently used languages stats
          plugin_languages_recent_load: 1000                            # Load up to 500 events to compute recently used stats
          plugin_languages_recent_days: 365                          
          plugin_achievements_threshold: C
          plugin_isocalendar: yes
          plugin_isocalendar_duration: year
          plugin_pagespeed: yes
          plugin_pagespeed_detailed: yes                                        
          plugin_pagespeed_url: .user.website
          plugin_lines: yes
          plugin_gists: yes
